services:
  - type: web
    name: esp32-display-api
    env: python
    region: oregon
    plan: free
    buildCommand: "cd api && pip install -r requirements.txt"
    startCommand: "cd api && python main.py"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DB_PATH
        value: /tmp/app.db
      - key: APP_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: PORT
        value: "8000"